### ISSUE TITLE
DETAIL SCREEN SCROOL CRASH

### ISSUE THREAD

**Issue by cengiztoru** [halilozcan/AnimeArch#13]
The app **CRASH**es when trying to scroll the detail screen when **DESCRIPTION** of the anime item **is SHORT**.

Please see the 2nd anime in the video.

https://user-images.githubusercontent.com/28221219/207709124-e7e5319b-d80e-47d2-afd5-2851306fe11a.mp4

**Comment by halilozcan** [comment]
Fixed

**Comment by cengiztoru** [comment]
> Fixed

Thanks 🤗 😍
